### PR TITLE
Track changed files and only download files that need to be updated

### LINKED ISSUE #9: Only download changed files
When your project starts to get big, downloading can take a while. We could try to be smart and only download files that have changed locally since the last time we downloaded.

### PR DESCRIPTION
**Pull request by WasabiFan**
This is most of a working implementation, however there are likely quirks as I haven't gotten a chance to test it thoroughly after fixing some early bugs.

TODO:
- [ ] Implement the logic to filter based on include/exclude paths. As far as I can tell, there isn't any provided method from vscode to match a glob pattern, so I think I need to check what module they use internally and add that as a dependency.
- [ ] Properly test deleting files/folders.
  - For reasons I can't explain, some combination of the things I have done to my environment has made it impossible to delete some folders I am working with (I lose permissions to the directory and Windows/NTFS disallow me from taking control, even as an admin). Suspiciously, I can only repro this so far after using the ev3dev extension with this patch included on the directories in question. I need to dig into this at some point.
- [ ] Do something about files that you delete locally while the extension isn't running

Fixes #9

### CODE REVIEW

**Comment by dlech** [comment]
It sounds like you are pretty busy right now, so if it is OK with you, I'll just take this as-is and fix it up as needed.

**Comment by WasabiFan** [comment]
Sounds good to me! If you'd like to, you can push to this PR branch, otherwise feel free to take the commits and use them as you wish.

**Comment by dlech** [comment]
I've never been able to figure out how to push to a pull request that I did not create.

I worked on this a bit last night, but I am realizing that with this approach, there are too many cases that are not handled. So, for the time being, I think I am going to start a new branch and try something else.

**Comment by WasabiFan** [comment]
@dlech agreed; I find this approach unnecessarily complicated. Something more like what rsync does with comparing modification dates might work better.

**Pull request closed without merging**
